package io.ktor.start.features

val ALL_FEATURES = listOf(
    HtmlDslFeature,
    CssDslFeature,
    FreemarkerFeature,
    VelocityFeature,
    StaticContentFeature,
    AuthFeature,
    AuthBasicFeature,
    AuthDigestFeature,
    AuthJwtFeature,
    AuthLdapFeature,
    AuthOauthFeature,
    JsonGsonFeature,
    JsonJacksonFeature,
    LocationsFeature,
    MetricsFeature,
    SessionsFeature,
    CompressionFeature,
    CachingHeadersFeature,
    CallLoggingFeature,
    ConditionalHeadersFeature,
    CORSFeature,
    DataConversionFeature,
    DefaultHeadersFeature,
    ForwardedHeaderSupportFeature,
    HSTSFeature,
    StatusPagesFeature,
    RoutingFeature,
    HttpsRedirectFeature,
    ShutdownUrlFeature,
    WebsocketsFeature,
    HttpClientFeature,
    RawSocketsFeature,
    PartialContentFeature,
    RawSocketsTlsFeature
)
